# ansible-playbook -K %s
---
-
  hosts:
      localhost
  connection: local
  tasks:
    - name: Create repo ref
      become: yes
      when: ansible_facts['distribution'] == "Fedora"
      get_url:
        dest: "/etc/yum.repos.d/cuda-fedora29.repo"
        mode: 0644
        url: https://developer.download.nvidia.com/compute/cuda/repos/fedora29/x86_64/cuda-fedora29.repo
    - name: Install Cuda
      become: yes
      when: ansible_facts['distribution'] == "Fedora"
      dnf:
        name:
          - cuda
          - cuda-drivers
        state: present

# dnf copr enable kiwizart/cuda-gcc-10.1
# dnf install cuda-gcc cuda-gcc-c++
# # For fedora32 at least
# ln -s /usr/lib64/libmpfr.so.6 /usr/lib64/libmpfr.so.4
